[2025-05-02 13:39:22] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /all_logs - –ö–æ–º–∞–Ω–¥–∞: /all_logs (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:40:46] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:43:27] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 13:43:27] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 13:43:27] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:48:34] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 13:48:34] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 13:48:34] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:49:50] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 13:49:50] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 13:49:50] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:51:48] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 13:51:48] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 13:51:48] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:52:27] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 13:52:27] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 13:52:27] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:52:48] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /bot_users - –ö–æ–º–∞–Ω–¥–∞: /bot_users (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:53:03] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /add_user - –ö–æ–º–∞–Ω–¥–∞: /add_user (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:53:03] 854825784 - –ó–∞–ø—É—Å—Ç–∏–ª –ø—Ä–æ—Ü–µ—Å—Å –¥–æ–±–∞–≤–ª–µ–Ω–∏—è –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è - –ö–æ–º–∞–Ω–¥–∞ /add_user (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:53:05] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /add_user - –ö–æ–º–∞–Ω–¥–∞: confirm_add_user (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:53:06] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /add_user - –ö–æ–º–∞–Ω–¥–∞: select_group_6 (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:53:06] 854825784 - –í—ã–±—Ä–∞–ª –≥—Ä—É–ø–ø—É –¥–ª—è –¥–æ–±–∞–≤–ª–µ–Ω–∏—è –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è - –ì—Ä—É–ø–ø–∞: –¢–æ—á–∫–∏ —Å –≤–∫—É—Å–Ω–æ–π –ø–æ–ª–∫–æ–π. (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:53:39] 854825784 - –î–æ–±–∞–≤–∏–ª –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è –≤ –≥—Ä—É–ø–ø—É - –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å: –î–æ—Å—Ç–∞–≤–∫–∞ UPPETIT (ID: 6691368671), –ì—Ä—É–ø–ø–∞: –¢–æ—á–∫–∏ —Å –≤–∫—É—Å–Ω–æ–π –ø–æ–ª–∫–æ–π. (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:53:47] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /bot_users - –ö–æ–º–∞–Ω–¥–∞: /bot_users (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:54:10] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: /set_task_group (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:54:11] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: select_task_type_daily (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:54:16] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: set_task_groups_daily (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:54:18] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: select_group|f3dc48f732 (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:54:20] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: select_group|ba25027277 (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:54:21] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: finish_group_selection (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:54:25] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: /set_task_group (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:54:30] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: select_task_type_daily (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:54:31] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: set_task_text_daily (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:54:56] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_time - –ö–æ–º–∞–Ω–¥–∞: /set_time (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:54:57] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_time - –ö–æ–º–∞–Ω–¥–∞: change_time (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:55:04] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 13:55:09] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:55:30] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /tasks_list - –ö–æ–º–∞–Ω–¥–∞: /tasks_list (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:55:42] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /start - –ö–æ–º–∞–Ω–¥–∞: /start (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 13:55:42] 854825784 - –ó–∞–ø—É—Å—Ç–∏–ª –±–æ—Ç–∞ - –ö–æ–º–∞–Ω–¥–∞ /start –æ—Ç –ü—ë—Ç—Ä (p_50104)
[2025-05-02 13:55:49] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /all_logs - –ö–æ–º–∞–Ω–¥–∞: /all_logs (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:05:13] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:05:13] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:05:16] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /all_logs - –ö–æ–º–∞–Ω–¥–∞: /all_logs (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:05:32] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_time - –ö–æ–º–∞–Ω–¥–∞: /set_time (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:05:36] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_time - –ö–æ–º–∞–Ω–¥–∞: change_time (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:05:41] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:05:46] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:06:01] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /bot_users - –ö–æ–º–∞–Ω–¥–∞: /bot_users (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:06:21] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /my_id - –ö–æ–º–∞–Ω–¥–∞: /my_id (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:06:27] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /add_user - –ö–æ–º–∞–Ω–¥–∞: /add_user (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:06:27] 854825784 - –ó–∞–ø—É—Å—Ç–∏–ª –ø—Ä–æ—Ü–µ—Å—Å –¥–æ–±–∞–≤–ª–µ–Ω–∏—è –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è - –ö–æ–º–∞–Ω–¥–∞ /add_user (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:06:29] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /add_user - –ö–æ–º–∞–Ω–¥–∞: confirm_add_user (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:06:30] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /add_user - –ö–æ–º–∞–Ω–¥–∞: select_group_5 (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:06:30] 854825784 - –í—ã–±—Ä–∞–ª –≥—Ä—É–ø–ø—É –¥–ª—è –¥–æ–±–∞–≤–ª–µ–Ω–∏—è –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è - –ì—Ä—É–ø–ø–∞: –ì—Ä—É–ø–ø–∞ ‚Ññ 6 (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:06:41] 854825784 - –î–æ–±–∞–≤–∏–ª –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è –≤ –≥—Ä—É–ø–ø—É - –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å: –ü—ë—Ç—Ä (ID: 854825784), –ì—Ä—É–ø–ø–∞: –ì—Ä—É–ø–ø–∞ ‚Ññ 6 (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:06:46] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /bot_users - –ö–æ–º–∞–Ω–¥–∞: /bot_users (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:07:02] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:07:46] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /tasks_list - –ö–æ–º–∞–Ω–¥–∞: /tasks_list (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:08:11] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: /set_task_group (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:08:12] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: select_task_type_weekly (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:08:23] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: set_task_text_weekly (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:08:39] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_day - –ö–æ–º–∞–Ω–¥–∞: /set_day (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:08:49] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:08:51] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:09:37] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:09:37] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:09:40] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:10:17] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6885679242 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:10:17] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7767503418 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:10:18] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6997091244 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:10:18] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6663438753 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:10:18] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6802455312 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:10:18] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7513265581 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:10:18] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7728654036 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:11:03] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /tasks_list - –ö–æ–º–∞–Ω–¥–∞: /tasks_list (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:11:23] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /bot_users - –ö–æ–º–∞–Ω–¥–∞: /bot_users (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:12:10] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /all_logs - –ö–æ–º–∞–Ω–¥–∞: /all_logs (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:12:42] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:13:02] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_day - –ö–æ–º–∞–Ω–¥–∞: /set_day (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:13:12] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:15:01] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6885679242 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:15:02] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7767503418 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:15:02] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6997091244 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:15:02] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6663438753 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:15:02] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6802455312 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:15:02] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7513265581 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:15:02] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7728654036 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:15:34] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_day - –ö–æ–º–∞–Ω–¥–∞: /set_day (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:15:48] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_day - –ö–æ–º–∞–Ω–¥–∞: /set_day (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:15:53] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:16:08] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:16:08] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:16:13] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:16:20] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /tasks_list - –ö–æ–º–∞–Ω–¥–∞: /tasks_list (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:16:27] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /clear_all_tasks_list - –ö–æ–º–∞–Ω–¥–∞: /clear_all_tasks_list (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:16:28] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /clear_all_tasks_list - –ö–æ–º–∞–Ω–¥–∞: clear_all_tasks_confirm (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:16:33] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /tasks_list - –ö–æ–º–∞–Ω–¥–∞: /tasks_list (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:17:08] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6885679242 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:17:09] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7767503418 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:17:09] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6997091244 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:17:09] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6663438753 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:17:09] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6802455312 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:17:09] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7513265581 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:17:10] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7728654036 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:19:09] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /all_logs - –ö–æ–º–∞–Ω–¥–∞: /all_logs (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:20:51] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /my_id - –ö–æ–º–∞–Ω–¥–∞: /my_id (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:28:12] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:28:12] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:28:39] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: /set_task_group (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:28:41] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: select_task_type_weekly (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:28:42] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: set_task_text_weekly (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:29:15] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_day - –ö–æ–º–∞–Ω–¥–∞: /set_day (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:29:24] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:29:38] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:29:38] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:29:49] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /all_logs - –ö–æ–º–∞–Ω–¥–∞: /all_logs (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:30:00] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:31:19] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6885679242 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:31:19] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7767503418 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:31:19] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6997091244 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:31:19] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6663438753 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:31:19] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6802455312 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:31:19] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7513265581 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:31:19] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–Ω–µ–¥–µ–ª—å–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7728654036 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 60, in send_weekly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–Ω–µ–¥–µ–ª—å–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:32:00] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /tasks_list - –ö–æ–º–∞–Ω–¥–∞: /tasks_list (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:32:09] 6691368671 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /photo_submission - –ö–æ–º–∞–Ω–¥–∞: None (–∞–¥–º–∏–Ω: –î–æ—Å—Ç–∞–≤–∫–∞ UPPETIT)
[2025-05-02 14:32:12] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /photo_submission - –ö–æ–º–∞–Ω–¥–∞: accept_7321_6691368671_7316 (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:32:16] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /tasks_list - –ö–æ–º–∞–Ω–¥–∞: /tasks_list (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:32:23] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /clear_tasks_list - –ö–æ–º–∞–Ω–¥–∞: /clear_tasks_list (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:32:24] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /clear_tasks_list - –ö–æ–º–∞–Ω–¥–∞: clear_tasks_confirm (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:32:28] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /tasks_list - –ö–æ–º–∞–Ω–¥–∞: /tasks_list (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:32:36] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: /set_task_group (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:32:38] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: select_task_type_monthly (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:32:40] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_task_group - –ö–æ–º–∞–Ω–¥–∞: set_task_text_monthly (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:32:57] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_month - –ö–æ–º–∞–Ω–¥–∞: /set_month (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:33:04] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:33:08] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:33:14] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_group_name - –ö–æ–º–∞–Ω–¥–∞: /set_group_name (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:33:15] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_group_name - –ö–æ–º–∞–Ω–¥–∞: confirm_set_group_name (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:33:18] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /set_group_name - –ö–æ–º–∞–Ω–¥–∞: select_group_to_rename|5 (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:33:27] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /show_schedule - –ö–æ–º–∞–Ω–¥–∞: /show_schedule (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:33:46] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:33:46] –°–ò–°–¢–ï–ú–ê - –ë–æ—Ç –±—ã–ª –ø–µ—Ä–µ–∑–∞–ø—É—â–µ–Ω
[2025-05-02 14:35:06] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7767503418 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:06] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7513265581 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:06] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6921154167 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:07] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7976143281 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:07] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6835324617 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:07] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 5766022670 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:07] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 5837809086 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:07] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6407412450 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:07] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 5892356945 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:07] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6881912887 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:07] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6784100812 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:07] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 5594387545 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:07] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6885679242 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:08] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 8111875232 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:08] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7924656411 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:08] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7813647980 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:08] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7002052320 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:08] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6997091244 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:08] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7337149118 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:08] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7402596646 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:08] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7155127106 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:09] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7688877305 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:09] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6310782529 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:09] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7204069526 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:10] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7404436505 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:10] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6802455312 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:10] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 5334735477 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:10] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6591425034 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:10] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7371163196 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:10] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6827347184 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:11] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7181711563 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:11] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7300925258 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:11] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 6663438753 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:11] –û–®–ò–ë–ö–ê –≤ –ø—Ä–∏ –æ—Ç–ø—Ä–∞–≤–∫–µ –µ–∂–µ–º–µ—Å—è—á–Ω–æ–π –∑–∞–¥–∞—á–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é 7728654036 - –¢–∏–ø: ApiTelegramException, –°–æ–æ–±—â–µ–Ω–∏–µ: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
–¢—Ä–∞—Å—Å–∏—Ä–æ–≤–∫–∞:
Traceback (most recent call last):
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/restart_scheduler.py", line 89, in send_monthly_tasks
    msg = bot.send_message(user_id, f"üìå <b>–ï–∂–µ–º–µ—Å—è—á–Ω–∞—è –∑–∞–¥–∞—á–∞:</b>\n{task_text}", parse_mode="HTML")
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/petrpopov/Documents/PycharmProjects/pythonProjects/UPPETIT_Task_Bot/.venv/lib/python3.13/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

[2025-05-02 14:35:20] 6691368671 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /photo_submission - –ö–æ–º–∞–Ω–¥–∞: None (–∞–¥–º–∏–Ω: –î–æ—Å—Ç–∞–≤–∫–∞ UPPETIT)
[2025-05-02 14:35:27] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /photo_submission - –ö–æ–º–∞–Ω–¥–∞: accept_7352_6691368671_7350 (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
[2025-05-02 14:35:34] 854825784 - –í—ã–ø–æ–ª–Ω–∏–ª –∫–æ–º–∞–Ω–¥—É /tasks_list - –ö–æ–º–∞–Ω–¥–∞: /tasks_list (–∞–¥–º–∏–Ω: –ü—ë—Ç—Ä)
